#!/bin/bash
#name: useGoogleDNS
#author: Generic
#description: Use Google DNS
#version: 1.0
#root: yes
#category: network
#distro: debbased
sudo echo "8.8.8.8" > /etc/resolv.conf
sudo echo "8.8.4.4" >> /etc/resolv.conf
